### PR TITLE
Add SteamVR support, fix unit rotation

### PR DESCRIPTION
**Pull request by PeridexisErrant**
Unit sprites now rotate to face the camera, rather than matching the rotation of the camera (which produced a disturbing parallax effect in VR.  Imported the SteamVR toolkit.  Added the [VRTK toolkit](https://github.com/thestonefox/SteamVR_Unity_Toolkit).

The result allows me to walk and teleport around in VR, exploring Dwarf Fortress in a way previously thought impossible.

However, there are a few issues and further enhancements I couldn't work out.

- a launch option is needed to use EITHER the present main camera (`CameraPivot/CameraHorizontalAxis/CameraCenter/`, which this pull request disables), OR the new `[CameraRig]` (required for VR support)

- For the world to be fully navigable in VR, climbing support is needed.  All this requires is attaching the `VRTK_InteractableObject` script to all claimable terrain (stairs, ramps, trees, etc) and change snap settings to `climbable` (instead of `FixedJoint`).  Unfortunately we couldn't find the right place to insert this change.

- As a requirement for VR support, we changed from deferred to forward rendering.  This could be made part of the camera toggle described above.

Future work should focus on making the menu accessible from VR mode (ie bound to the menu button on the controller and intractable), and supporting VR while zoomed-out to world scale.  More whimsically, a small pick could be attached to the controllers :smile:

Time to strike the virtual earth!

### CODE REVIEW

**Comment by JapaMala** [comment]
Regarding stairs, right now, they're managed by translating the position of the feet into a a collision info enum, which says if it's stairs, water, solid, or air. Could that be used for the VR script?

**Comment by JapaMala** [comment]
Also, what's the reason for needing to use forward rendering? Is it just because of Antialiasing?

**Comment by PeridexisErrant** [comment]
Forward rendering is because deferred simply doesn't work in the VR pipelines and at the required framerate - I don't entirely understand it myself, but there's black GPU magic happening.  AA is part of the answer, but shaders and lens-correction are bigger.

Not a Unity expert, but anything you can attach that script to should work... so you may need to make more objects.  Or, if we don't mind *everything* being climbable (which it feels like it is sometimes...) you could just attach it to the whole mesh I guess?

**Comment by JapaMala** [comment]
Well, In DF, everything IS climbable, pretty much. 

Though right now, stairs have no colision meshes, but that's easy to change.

**Comment by PeridexisErrant** [comment]
Remaining things to do before a release can be made with these changes:

- [ ] Add setting to choose "Screen Mode" or "VR Mode" in resolution selector.  This should enable one of the two (mutually exclusive) camera systems, and may use deferred rendering for normal mode.
- [ ] Make things climbable, as above
- [ ] Have release-candidate tested on a Vive (I can help :smile: )

**Comment by JapaMala** [comment]
I'm pretty sure Unity has a VR mode commandline switch.

I'd probably use that.

**Comment by PeridexisErrant** [comment]
You could also test if a VR headset is attached, I guess, but commandline makes sense!

**Comment by JapaMala** [comment]
It's complaining about a bunch of things after I merged the code, so I'm trying re-importing the asset store and seeing if that fixed things.

**Comment by PeridexisErrant** [comment]
That's why I did it as two commits!  Are you on Unity 5.4?  I think the rendered requires that.

The only settings you need to accept when importing are the forward rendering, and the GPU setting (I forget the exact name)

**Pull request merged**
