### PR TITLE
Added nest box Mesh

### PR DESCRIPTION
**Pull request by clickworkorange**

### CODE REVIEW

**Comment by JapaMala** [comment]
Your alpha map is the wrong format. It needs to be white where the texture is opaque, and black where it's transparent.

Also, the metallic map shouldn't be following the alpha map, since that can lead to funny looking artifacts. Just have a flat block of color where the grille is.

It's also not necessary to put the gradient into the grille color, because the reflections are added in-game.

I'll pull this as-is, and made the changes myself, but this is something to keep in mind.

**Comment by clickworkorange** [comment]
Ok, many thanks for the info, very helpful! I've taken your comments wrt size on board, and I also see how I can improve the mapping - expect an updated version in the next 24h. I really need to get the meshes to display inside AV first though - otherwise it's all too much guesswork!

**Comment by clickworkorange** [comment]
Should I be providing an AO map as well? I see that many of your meshes have this... I might need to start baking AO, and maybe normals too.

**Comment by clickworkorange** [comment]
Oh and it should probably be rotated by 90 degress clockwise on the Z axis...

**Pull request merged**
