### PR TITLE
Multithreading

### PR DESCRIPTION
**Pull request by kazimuth**
Start making things multithreaded.
I'm starting out by splitting GameMap into smaller classes with async-style interfaces; submit requests each frame, and pull updates from a completed task queue each frame. These can be switched to use multithreading internally later.

There's some unnecessary stuff in here right now, I'll remove it. This is very much not ready to merge in general, I just wanted to make sure you're aware of it.

### CODE REVIEW

**Comment by JapaMala** [comment]
I noticed that you merged the camera assembly into a single object, or at
least that's what it looks like from the scripts. Don't do this. It's
important that there is a different object for each Axis of rotation, to
make movement easier, and to make sure the rotation stays predictable.

**Comment by kazimuth** [comment]
Okay, I'm removing that now.

Any other things I should avoid? I'm still pretty new at Unity.

**Comment by kazimuth** [comment]
Next I'm planning on pulling the meshing code from `GameMap` into a new class - `MeshFactory` or something.
Instead of just updating the meshes each frame, `GameMap` will submit `BlockMeshRequest` structs to its member factory, call `factory.Process()` each frame, and fetch the newly created meshes with `factory.PopMeshUpdate()`. The factory will start out doing the meshing synchronously, but it can be switched to using a `ThreadPool` for work later.

Does this seem reasonable? I'm trying to avoid making GameMap into a tangled mess of mutexes and other threading nonsense.

**Comment by JapaMala** [comment]
Yeah, separating the mesher from gamemap is a good idea. Maybe even making
the central map storage a singleton, to ease access?

**Comment by kazimuth** [comment]
I was thinking of doing that, actually. It shouldn't ever be necessary to have multiple maps, right?

**Comment by kazimuth** [comment]
I was making the MapDataStore static, but I realized that if we want to mesh things in multiple threads then we'll need to mediate access to it somehow. Having loads of contention over a single array didn't seem like a good idea, so I made MapDataStore sliceable; there's one that represents the main map, but smaller ones can be created to hold smaller chunks of the map, and handed off to meshing threads.

I also made MapTile a struct, even if it wasn't super necessary, and moved it to MapDataStore.Tile (since they're kinda inseparable now).

**Comment by kazimuth** [comment]
Things are coming along! Currently fixing some bugs with coordinates in the new meshing system, then I'll move on to the actual threading part.

**Comment by kazimuth** [comment]
This works! Stuff runs silky-smooth.
No tests or anything but we don't have those yet anyway.

**Pull request merged**
